---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mqgiebhw/public_html/sdcreations/
    - export PATH=/opt/alt/alt-nodejs20/root/usr/bin:$PATH
    - cd /home/mqgiebhw/repositories/sd-creations
    - npm install
    - npm run build
    - /bin/cp -R dist/. $DEPLOYPATH